# ISSUE 87
#
# Problem:
# Write a program that accepts product sales records and calculates the revenue generated by each product and identifies products generating more than the average revenue.
#
# This file contains an incomplete implementation.
# Do not rewrite the program from scratch.
#
# Find and repair the mistakes marked with TODO comments.
#
# After repairing the code, run this file and make sure all
# checks pass before submitting your Pull Request.

def product_revenue_report(sales):
    revenue = {}
    for sale in sales:
        # TODO: Check how quantity and price are combined.
        amount = sale["quantity"] + sale["price"]
        product = sale["product"]
        revenue[product] = revenue.get(product, 0) + amount
    average = sum(revenue.values()) / len(revenue) if revenue else 0
    # TODO: Check which products exceed the average revenue.
    above_average = [name for name, amount in revenue.items() if amount >= average]
    return revenue, above_average

def check_solution():
    sales = [{"product":"pen","quantity":10,"price":2},{"product":"book","quantity":2,"price":15},{"product":"pen","quantity":5,"price":2}]
    assert product_revenue_report(sales) == ({"pen":30,"book":30},["pen","book"])
    assert product_revenue_report([]) == ({},[])

    print("All checks passed!")

if __name__ == "__main__":
    check_solution()
