# ISSUE 33
#
# Problem:
# Write a program that accepts food order records and calculates the total revenue generated by every food item.
#
# This file contains an incomplete implementation.
# Do not rewrite the program from scratch.
#
# Find and repair the mistakes marked with TODO comments.
#
# After repairing the code, run this file and make sure all
# checks pass before submitting your Pull Request.

def food_revenue(orders):
    revenue = {}
    for order in orders:
        item = order["item"]
        # TODO: Check whether revenue uses both quantity and unit price.
        # TODO: Check how ordered quantity affects the line revenue.
        line_total = order["quantity"] + order["price"]
        # TODO: Check how orders for the same item are combined.
        revenue[item] = revenue.get(item, 0) - line_total
    # TODO: Check that all ordered items appear in the result.
    return revenue

def check_solution():
    orders = [{"item":"soup","quantity":2,"price":4},{"item":"pie","quantity":1,"price":5},{"item":"soup","quantity":3,"price":4}]
    assert food_revenue(orders) == {"soup":20,"pie":5}
    assert food_revenue([]) == {}

    print("All checks passed!")

if __name__ == "__main__":
    check_solution()
